### ISSUE TITLE
threebot stop doesn't fully exit nginx

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#137]
![Screenshot from 2020-06-29 19-36-58](https://user-images.githubusercontent.com/10658229/86037637-f7200c00-ba3f-11ea-8325-4607524df4c9.png)

although I did systemctl disable nginx

**Comment by grimpy** [comment]
how does systemctl relate? Afaik we don't start nginx with systemd

**Comment by xmonader** [comment]
> Afaik we don't start nginx with systemd

i think because of the nginx postscript, nginx.service gets registered and activated in general

**Comment by xmonader** [comment]
I reread, it's nginx capturing 8999, which is not a standard thing nginx does, so looks like it has nothing to do with systemd at all

**Comment by waleedhammam** [comment]
fixed by: https://github.com/threefoldtech/js-sdk/pull/139

**Comment by Dina-Abd-Elrahman** [comment]
- still the same error. 

Commit_ID:  2732f0a883c9a0fb22332dbebe24ee6aabe48bf3

**Comment by xmonader** [comment]
the workflow changed

please test with `threebot start --local` for normal user and if u have root permissions try with `threebot start`

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
