### ISSUE TITLE
VDC 'deployed workloads' gives blank screen

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2884]
VDC running, deployed a Presearch node. And it runs as the nodepage is accessible after deployment. 

But button 'DEPLOYED WORKLOADS' gives a blank screen. 

![image](https://user-images.githubusercontent.com/30384423/113887561-e320ec00-97c1-11eb-8ca5-3eec9de3b49a.png)

Browsers tried: Firefox, Brave (blank screen in both)
3bot: homesteadhacker
VDC: homestea

**Comment by dmahmouali** [comment]
@gmachtel 
please update the dashboard, it should be fixed in this [commit](https://github.com/threefoldtech/js-sdk/commit/53857900e235f294140d845dacd96b86716fa891).

**Comment by gmachtel** [comment]
Seems it's not solved. 

![image](https://user-images.githubusercontent.com/30384423/114190092-33778580-994b-11eb-8632-baea3648ec1a.png)

**Comment by gmachtel** [comment]
issue solved now
